### ISSUE TITLE
external site redirect view is applied to pages footer links

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix-pages#18]
When setting 
![image](https://user-images.githubusercontent.com/5970076/153456207-ac1bf418-699b-454f-8657-74f9545cbe85.png)

`/redirect/?url=` is applied to the link in the footer, at least on my event with a custom domain.

This probably is a problem with the `pretix.presale.signals.footer_link` signal?!

**Comment by felixrindt** [comment]
Now I should add this is an issue to me because of the newly introduced "Continue to <external domain>" button, so now there's an extra step when navigating to pretix pages that are hosted on the same domain.

**Comment by raphaelm** [comment]
That sounds even more buggy, the "Continue to" button should only show up on cross-domain referrers :thinking:

**Comment by felixrindt** [comment]
So I figured out my setup and set the `X_FORWARDED_FOR` headers in the proxy and updated my pretix settings to trust them. Sorry for the noise.
