### ISSUE TITLE
pretix-pages plugin missing dependencies

### ISSUE THREAD

**Issue by adisbladis** [pretix/pretix-pages#9]
At the very least this package should depend on `pretix` so `django` & other dependencies are inherited from `pretix`.

As a matter of fact this seems to be a common problem with all plugin packages for pretix.

**Comment by raphaelm** [comment]
Hi,

this is intended this way. Adding ``pretix`` without a version would make it easy too to screw up your production environment by accidentally upgrading to a new major version of pretix and too easy to screw up your development environment by having two versions of pretix at the same time. Adding ``pretix`` with a pinned version would force all plugins to be updated with every pretix update, which is unfeasible.

Instead, we're slowly rolling out a pretix-level version check and a properly caught ``ImportError`` accross plugins: https://docs.pretix.eu/en/latest/development/api/plugins.html#plugin-metadata

I know it's not an ideal solution from a packaging point of view, but so far it works great in the real world.

**Comment by adisbladis** [comment]
This makes all pretix plugins impossible to package up automatically for other package ecosystems.

For NixCon (https://nixcon.org) we're using https://github.com/adisbladis/poetry2nix/ which automatically creates [Nix](https://nixos.org/nix/) packages based on projects managed with [Poetry](https://poetry.eustace.io/).

Every Nix build happens in isolation and only with the dependencies specified in the dependency graph for each individual package.
Since `pretix` is not listed as a dependency for `pretix-pages` this breaks our builds.

We _can_ override this in our Nix expressions:
``` nix
    pretix-pages = self: super: drv: drv.overrideAttrs(old: {
      propagatedBuildInputs = old.propagatedBuildInputs ++ [ self.pretix ];
    });
```

But it's far from ideal and we have to do this for every single plugin we want to use.

Wouldn't it be possible to add a versionless dependency on `pretix` and _also_ have the pretix-level version checks?

**Comment by raphaelm** [comment]
Hi, thanks for explaining your concerns, I can see why this is a problem.

However, as I said above, I fear that version-less dependencies make it easy to screw up when using pip.

Second, if everything is built in isolation and we add version-less dependencies and any plugin is in fact not compatible with the current version of pretix, your build will fail, which is not great either.

Third, we're not using Poetry either, so poetry2nix probably requires manual configuration on your side anyways?

That said, we will consider this and play around with it. However, it feels like a risky change and while I understand and admire that you're of course want to use proper Nix packages for NixCon, I'm sorry to say that we have no intention of officially supporting any kind of packaging other than the Python packaging ecosystem (directly or inside Docker). 

pretix often manually pins versions of of dependencies which makes it pretty unusable with most package manager (like dpkg or pacman) anyways and with virtual environments, Python provides a decent standardized way to isolate software projects. It's just too much work and too little to gain for us as a project

I know that Nix wouldn't struggle with this specific problem and that you are not asking us to publish Nix packages ourselves, but I hope you can understand why this has very low priority for us.

**Comment by adisbladis** [comment]
> Second, if everything is built in isolation and we add version-less dependencies and any plugin is in fact not compatible with the current version of pretix, your build will fail, which is not great either.

I'd prefer this failure mode over the current state where the dependency is simply not there.

> Third, we're not using Poetry either, so poetry2nix probably requires manual configuration on your side anyways?

Yes it does. In case you are interested to have a look we have published our configurations here:
https://github.com/nixcon/nixcon-vps/tree/master/pkgs/pretix

> I'm sorry to say that we have no intention of officially supporting any kind of packaging other than the Python packaging ecosystem (directly or inside Docker).

I understand that we are on our own here. No worries.

> I know that Nix wouldn't struggle with this specific problem and that you are not asking us to publish Nix packages ourselves, but I hope you can understand why this has very low priority for us.

Completely understandable :) For now I'll just apply overrides to our Nix expressions.

Thanks for your time and consideration!
Also: If you'd like to feel free to list us as users on https://pretix.eu if you'd like.
